language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"
  
script:
  - docker --version # for loggin purpose, print the version
  - docker build -t simple-express .
  - docker tag simple-express freeborniwarri/simple-express:latest

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push freeborniwarri/simple-express:latest